### ISSUE TITLE
[Epic] Move locally created scripts to Github

### ISSUE THREAD

**Issue by ivansoft** [ivansoft/template-ghpages-site#1]
Tasks:

- [ ] Reorganize project's files. New Project's structure.
- [ ] Prepare LUA path and cpath
- [ ] Move modified external Lua/C-dependecies to separate projects (fork them if they have been already created on Github)
- [ ] Think about how to include the features: how to turn on / turn off features to the final Project/Repo:
  - branch-based features support
  - repo-based features support
  - example: repo 'qlua-library', branches: 'console', 'logfile', 'quik_callbacks_logging'
    - `git remote add qlua_library git@github.com:ivansoft/qlua-library.git`
    - `git merge qlua_library/logfile`
    - `git merge qlua_library/quik_callbacks_logging`
